// Map countries to their currency codes (alphabetized)
const countryCurrency = {
  Argentina: "ARS",
  Australia: "AUD",
  Bangladesh: "BDT",
  Belgium: "EUR",
  Brazil: "BRL",
  Canada: "CAD",
  China: "CNY",
  Czechia: "CZK",
  Denmark: "DKK",
  Egypt: "EGP",
  France: "EUR",
  Germany: "EUR",
  Hungary: "HUF",
  India: "INR",
  Indonesia: "IDR",
  Italy: "EUR",
  Japan: "JPY",
  Malaysia: "MYR",
  Mexico: "MXN",
  Netherlands: "EUR",
  NewZealand: "NZD",
  Nigeria: "NGN",
  Norway: "NOK",
  Pakistan: "PKR",
  Philippines: "PHP",
  Poland: "PLN",
  Russia: "RUB",
  SaudiArabia: "SAR",
  Singapore: "SGD",
  SouthAfrica: "ZAR",
  SouthKorea: "KRW",
  Spain: "EUR",
  Sweden: "SEK",
  Switzerland: "CHF",
  Thailand: "THB",
  Turkey: "TRY",
  UAE: "AED",
  UK: "GBP",
  USA: "USD",
  Vietnam: "VND",
  // Add more as needed
};

export default countryCurrency;
